#!/usr/bin/env python
""" vtk2nii

Python command line interface for converting vtk polydata to nifti using
Camino. Outputs image with number of streamlines through voxel, raw
streamline counts, and binary mask of tract.

**NOTE**
REQUIRES INSTALLATION OF CAMINO AND ABILITY TO CONVERT FROM VTK TO BFLOAT
WORKS WITH SINGULARITY CONTAINER (RECIPE CAN BE FOUND IN GIT REPO:
https://github.com/kaitj/neurobeer)

"""
def getBIDS(bids_layout, subjid, ref_img):
    subjid = subjid.lstrip('sub-')

    # Grab necessary files
    nii = bids_layout.get(subject=subjid, type=ref_img,
                             return_type='file', extensions=['nii', 'nii.gz'])

    return nii[0]


def proc_cmd(cmd):
    procCmd = cmd.split(" ")

    return procCmd


def get_parser():
    """
    Argument Parser
    """
    from argparse import ArgumentParser, RawTextHelpFormatter
    from neurobeer._version import __version__

    parser = ArgumentParser(description=('Converts VTK polydata tractography '
                                         'to nifti'),
                            formatter_class=RawTextHelpFormatter)

    # Version option
    parser.add_argument('--version', action='version', version=__version__)

    # Required arguments
    g_req = parser.add_argument_group('required arguments')
    g_req.add_argument('nii_dir', help='Directory with input dataset, '
                                        'formatted according to BIDS standard')
    g_req.add_argument('vtk_dir', help='Derivatives directory where VTKs are '
                                       'located')
    g_req.add_argument('vtk_file', help='VTK file to be converted. Searches in '
                                        'tractography folder under subject. '
                                        '<vtk_dir>/<subj>/tractography/<vtk_file>')
    g_req.add_argument('subjid', help='Participant id to track')
    g_req.add_argument('ref_img', help='Nifti image to use as reference for '
                                       'header (eg. fa, t1, etc.)')

    # Optional arguments
    g_opt = parser.add_argument_group('control arguments')
    g_opt.add_argument('-o', '--out_dir', dest="out_dir",
                                          help="Output directory. Defaults to "
                                            "<bids_dir>/derivatives/camino")
    g_opt.add_argument('-r', '--resamplestepsize', dest="resamplestepsize",
                                                   help="Sample size for for "
                                                        "tracking streamlines ")
    g_opt.add_argument('-v', '--verbose', action='count', default=0,
                       help='verbosity of tool')

    return parser


def main():
    """
    Entry point of code
    """
    import os
    import os.path as op
    import subprocess

    from bids.grabbids import BIDSLayout
    from neurobeer.tractograhy import misc

    args = get_parser().parse_args()
    # Required inputs
    nii_dir = args.nii_dir
    subjid = args.subjid
    vtk_dir = args.vtk_dir
    vtk_file = args.vtk_file
    ref_img = args.ref_img

    if args.resamplestepsize:
        resamplestepsize = float(args.resamplestepsize)
    else:
        resamplestepsize = 0.1

    # Set output directory
    if args.out_dir:
        out_dir = op.realpath(args.out_dir)
        out_dir = op.join(op.join(out_dir, subjid), 'tractography')
    else:
        out_dir = op.join(op.join('derivatives/camino', subjid),
                                  'tractography')
        out_dir = op.join(op.realpath(nii_dir), out_dir)

    if not op.exists(out_dir):
        os.makedirs(out_dir)

    in_vtk = op.join(op.join(op.join(vtk_dir, subjid), 'tractography'),
                vtk_file)

    # Set file defaults
    filename = op.splitext(in_vtk)[-2]
    filename = filename.split('/', -1)[-1]

    # Grab necessary files
    layout = BIDSLayout(nii_dir)
    nii = getBIDS(layout, subjid, ref_img)

    # Read vtk and convert to bfloat
    vtk_str = '"{}"'.format(in_vtk)
    bfloat = filename + '.Bfloat'
    bfloat = op.join(out_dir, bfloat)
    bfloat_str = '"{}"'.format(bfloat)
    cmd = proc_cmd("runOctaveCmd writeCaminoTracts readTractsFromVTK(%s) %s"
                    % (vtk_str, bfloat_str))
    conv_proc = subprocess.Popen(cmd,
                                 stdout=open(os.devnull, 'wb')).communicate()

    if conv_proc[0] is not None or not op.exists(bfloat):
        raise RuntimeError("Error converting .vtk to .bfloat")

    misc.vprint("Converting tractography to nifti...", args.verbose)

    # Process streamlines
    out_root = filename + '_'
    out_root = op.join(out_dir, out_root)

    bfloat_in = open(bfloat)
    cmd = proc_cmd("procstreamlines -header %s -resamplestepsize %f "
                   "-outputacm -outputsc -outputroot %s" %
                   (nii, resamplestepsize, out_root))
    streamlines_proc = subprocess.Popen(cmd, stdin=bfloat_in,
                                       stdout=open(os.devnull, 'wb')).communicate()

    if streamlines_proc[0] is not None:
        raise RuntimeError("Error converting to nifti.")

    misc.vprint("Binarizing generated tractography mask", args.verbose)

    # Binarize mask
    out_nii = filename +'.nii.gz'
    out_nii = op.join(out_dir, out_nii)

    out_acm = filename + '_acm_sc.nii.gz'
    out_acm = op.join(out_dir, out_acm)

    cmd = proc_cmd("fsl5.0-fslmaths %s -bin %s" % (out_acm, out_nii))
    fsl_proc = subprocess.Popen(cmd,
                                stdout=open(os.devnull, 'wb')).communicate()

    if fsl_proc[0] is not None:
        raise RuntimeError("Error binarizing tractography mask")


if __name__ == '__main__':
    main()
